hmrc/digital-platform-reporting-register-frontend

app/pages/AddressInUkPage.scala
app/views/AddressInUkView.scala.html
conf/app.routes
conf/messages.en
test/controllers/AddressInUkControllerSpec.scala
test/pages/AddressInUkPageSpec.scala

- updated page view with correct text/layout
- updated navigation to next page depending on answer
- updated relevant tests
<details>
<summary>Screenshot of screen</summary>
</details>

Update to live-in-uk boolean question page

---

app/controllers/BusinessNameController.scala
app/controllers/IsThisYourBusinessController.scala
app/controllers/SoleTraderNameController.scala
app/models/UserAnswers.scala
app/models/registration/requests/IndividualWithUtr.scala
app/models/registration/requests/OrganisationWithUtr.scala
project/AppDependencies.scala
test/controllers/BusinessNameControllerSpec.scala
test/controllers/DetailsMatchedControllerSpec.scala
test/controllers/IsThisYourBusinessControllerSpec.scala
test/controllers/SoleTraderNameControllerSpec.scala
test/controllers/UkAddressControllerSpec.scala
test/controllers/UtrControllerSpec.scala
test/forms/FormSpec.scala
test/models/registration/requests/IndividualWithUtrSpec.scala
test/models/registration/requests/OrganisationWithUtrSpec.scala
test/models/registration/requests/RegistrationRequestSpec.scala

Add calls to register with ID from the Sole Trader Name page and Business Name page.

Register with ID calls

---

conf/app.routes

[ODPR-1250] - DEV: REG-KO-1 URL Change.

---

app/controllers/BusinessNameController.scala
app/controllers/SoleTraderDetailsNotMatchController.scala
app/pages/BusinessNamePage.scala
app/pages/HasUtrPage.scala
app/pages/SoleTraderNamePage.scala
app/views/SoleTraderDetailsNotMatchView.scala.html
conf/app.routes
conf/messages.en
project/AppDependencies.scala
project/plugins.sbt
test/controllers/BusinessNameControllerSpec.scala
test/controllers/SoleTraderDetailsNotMatchControllerSpec.scala
test/pages/BusinessNamePageSpec.scala
test/pages/HasUtrPageSpec.scala
test/pages/SoleTraderNamePageSpec.scala

- Created kick out page: Sole trader details not matched page
- Updated navigation from sole trader name & business name pages
[ODP-1184](https://jira.tools.tax.service.gov.uk/browse/ODPR-1184)
- [] Have you checked code coverage isn’t lower than previously?

[ODPR-1184]- Sole Trader Details Not Matched Page

---

app/controllers/SecondaryContactPhoneNumberController.scala
app/forms/SecondaryContactPhoneNumberFormProvider.scala
app/models/pageviews/SecondaryContactPhoneNumberViewModel.scala
app/pages/SecondaryContactPhoneNumberPage.scala
app/viewmodels/checkAnswers/SecondaryContactPhoneNumberSummary.scala
app/views/SecondaryContactPhoneNumberView.scala.html
conf/app.routes
conf/messages.en
test/controllers/SecondaryContactPhoneNumberControllerSpec.scala
test/forms/SecondaryContactPhoneNumberFormProviderSpec.scala
test/models/pageviews/SecondaryContactPhoneNumberViewModelSpec.scala
test/pages/SecondaryContactPhoneNumberPageSpec.scala

[ODPR-1125](https://jira.tools.tax.service.gov.uk/browse/ODPR-1125)

[ODPR-1125] - DEV-REG-3: Type of business.

---

conf/messages.en

[ODPR-1126](https://jira.tools.tax.service.gov.uk/browse/ODPR-1126)

[ODPR-1126] - DEV-REG-4: Organisation registered address in UK?.

---

app/forms/UtrFormProvider.scala
test/forms/UtrFormProviderSpec.scala

[ODPR-1128](https://jira.tools.tax.service.gov.uk/browse/ODPR-1128)

[ODPR-1128] - DEV- REG-6: Organisation what is your UTR?.

---

app/forms/IndividualNameFormProvider.scala
app/models/pageviews/CheckYourAnswersIndividualViewModel.scala
conf/app.routes
conf/messages.en
test/forms/IndividualNameFormProviderSpec.scala

[ODPR-1196] - DEV-REG-17. Individual name.

---

app/forms/DateOfBirthFormProvider.scala
conf/messages.en
test/forms/DateOfBirthFormProviderSpec.scala

[ODPR-1198] - DEV- REG-18. Individual Date of Birth.

---

app/forms/DateOfBirthFormProvider.scala
conf/messages.en
test/forms/DateOfBirthFormProviderSpec.scala

[ODPR-1198] - Minor update of error message.

---

app/connectors/SubscriptionConnector.scala
app/models/subscription/Contact.scala
app/models/subscription/requests/SubscriptionRequest.scala
app/models/subscription/responses/SubscriptionResponse.scala
it/test/connectors/RegistrationConnectorSpec.scala
it/test/connectors/SubscriptionConnectorSpec.scala
test/models/subscription/responses/SubscriptionResponseSpec.scala

Add a connector to call the subscribe endpoint

Add subscription connector

---

app/controllers/BusinessNameNoUtrController.scala
app/controllers/HasUtrController.scala
app/forms/BusinessNameNoUtrFormProvider.scala
app/models/pageviews/BusinessNameNoUtrViewModel.scala
app/pages/BusinessNameNoUtrPage.scala
app/pages/HasUtrPage.scala
app/viewmodels/checkAnswers/BusinessNameNoUtrSummary.scala
app/views/BusinessNameNoUtrView.scala.html
conf/app.routes
conf/messages.en
test/controllers/BusinessNameNoUtrControllerSpec.scala
test/controllers/HasUtrControllerSpec.scala
test/forms/BusinessNameNoUtrFormProviderSpec.scala
test/forms/HasUtrFormProviderSpec.scala
test/models/pageviews/BusinessNameNoUtrViewModelSpec.scala
test/pages/BusinessNameNoUtrPageSpec.scala
test/pages/HasUtrPageSpec.scala

[ODPR-1127](https://jira.tools.tax.service.gov.uk/browse/ODPR-1127)

[ODPR-1127] - DEV- REG-5: Organisation do you have UTR?.

---

app/pages/AddressInUkPage.scala
conf/app.routes
conf/messages.en
test/pages/AddressInUkPageSpec.scala

[ODPR-1199](https://jira.tools.tax.service.gov.uk/browse/ODPR-1199)

[ODPR-1199] - Dev- REG-20. Individual live in UK.

---

app/pages/BusinessNamePage.scala
app/pages/DetailsMatchedPage.scala
app/pages/SoleTraderNamePage.scala
conf/app.routes
test/pages/BusinessNamePageSpec.scala
test/pages/DetailsMatchedPageSpec.scala
test/pages/SoleTraderNamePageSpec.scala

- updated navigation from 'sole trader name' and 'business name' > if user is matched and not already subscribed, leads to details matched page
[ODPR-1180](https://jira.tools.tax.service.gov.uk/browse/ODPR-1180)

[ODPR-1180] - Update details matched page navigation

---

app/pages/InternationalAddressPage.scala
conf/app.routes
test/pages/InternationalAddressPageSpec.scala

[ODPR-1203](https://jira.tools.tax.service.gov.uk/browse/ODPR-1203)

[ODPR-1203] - Dev-REG-25. Individual international address entry.

---

app/forms/UkAddressFormProvider.scala
app/forms/common/UkPostCode.scala
app/models/Country.scala
app/models/UkAddress.scala
app/pages/UkAddressPage.scala
app/views/UkAddressView.scala.html
app/views/ViewUtils.scala
conf/app.routes
conf/messages.en
test-utils/generators/ModelGenerators.scala
test/controllers/UkAddressControllerSpec.scala
test/forms/UkAddressFormProviderSpec.scala
test/forms/UkPostCodeFormProviderSpec.scala
test/pages/UkAddressPageSpec.scala
test/views/ViewUtilsSpec.scala

- Fixes issues with existing uk address page: URL, error messages
- Added 'country' autocomplete text box with only UK countries
[ODPR-12104](https://jira.tools.tax.service.gov.uk/browse/ODPR-1204)

[ODPR-1204] - DEV-REG-24. Manual individual UK address

---

app/pages/AddressInUkPage.scala
test/pages/AddressInUkPageSpec.scala

[ODPR-1204] - Links temporarily to manual uk address.

---

app/controllers/BusinessHaveTradingNameController.scala
app/forms/BusinessHaveTradingNameFormProvider.scala
app/models/pageviews/BusinessHaveTradingNameViewModel.scala
app/pages/BusinessHaveTradingNamePage.scala
app/viewmodels/checkAnswers/BusinessHaveTradingNameSummary.scala
app/views/BusinessHaveTradingNameView.scala.html
conf/app.routes
conf/messages.en
test/controllers/BusinessHaveTradingNameControllerSpec.scala
test/forms/BusinessHaveTradingNameFormProviderSpec.scala
test/models/pageviews/BusinessHaveTradingNameViewModelSpec.scala
test/pages/BusinessHaveTradingNamePageSpec.scala

[ODPR-1137](https://jira.tools.tax.service.gov.uk/browse/ODPR-1137)

[ODPR-1137] - DEV: trade under a different name (ORG).

---

app/controllers/BusinessEnterTradingNameController.scala
app/forms/BusinessEnterTradingNameFormProvider.scala
app/models/pageviews/BusinessEnterTradingNameViewModel.scala
app/pages/BusinessEnterTradingNamePage.scala
app/viewmodels/checkAnswers/BusinessEnterTradingNameSummary.scala
app/views/BusinessEnterTradingNameView.scala.html
build.sbt
conf/app.routes
conf/messages.en
test/controllers/BusinessEnterTradingNameControllerSpec.scala
test/forms/BusinessEnterTradingNameFormProviderSpec.scala
test/models/pageviews/BusinessEnterTradingNameViewModelSpec.scala
test/pages/BusinessEnterTradingNamePageSpec.scala

[ODPR-1138](https://jira.tools.tax.service.gov.uk/browse/ODPR-1138)

[ODPR-1138] - DEV: business trading name.

---

app/controllers/BusinessDetailsMatchOtherController.scala
app/models/Country.scala
app/models/UserAnswers.scala
app/models/pageviews/BusinessDetailsMatchOtherViewModel.scala
app/models/registration/Address.scala
app/views/BusinessDetailsMatchOtherView.scala.html
conf/app.routes
conf/messages.en
test-utils/builders/AddressBuilder.scala
test-utils/builders/MatchResponseWithIdBuilder.scala
test-utils/builders/MatchResponseWithoutIdBuilder.scala
test-utils/helpers/UserAnswerHelper.scala
test/controllers/BusinessDetailsMatchOtherControllerSpec.scala
test/controllers/IsThisYourBusinessControllerSpec.scala
test/models/pageviews/BusinessDetailsMatchOtherViewModelSpec.scala
test/pages/IsThisYourBusinessPageSpec.scala

[ODPR-1223](https://jira.tools.tax.service.gov.uk/browse/ODPR-1223)

[ODPR-1223] - DEV:REG-KO-4. GG linked to another business.

---

app/forms/NinoFormProvider.scala
app/views/NinoView.scala.html
conf/messages.en
test-utils/generators/Generators.scala
test/controllers/NinoControllerSpec.scala
test/forms/NinoFormProviderSpec.scala

[ODPR-1194](https://jira.tools.tax.service.gov.uk/browse/ODPR-1194)

[ODPR-1194] - Update NINO page

---

conf/app.routes

[ODPR-1242](https://jira.tools.tax.service.gov.uk/browse/ODPR-1242)

ODPR-1242: Changed URL for NINO page

---

app/controllers/BusinessAlreadyRegisteredController.scala
app/pages/BusinessNamePage.scala
app/pages/SoleTraderNamePage.scala
app/views/BusinessAlreadyRegisteredView.scala.html
conf/app.routes
conf/messages.en
test/controllers/BusinessAlreadyRegisteredControllerSpec.scala
test/pages/BusinessNamePageSpec.scala

- created REG-KO-3
- updated navigation from businessName page
[ODPR-1172](https://jira.tools.tax.service.gov.uk/browse/ODPR-1172)

[ODPR-1172] - REG-KO-3: organisation already registered

---

conf/app.routes
conf/messages.en

- fixes to flagged issues during demo
[ODPR-1256](https://jira.tools.tax.service.gov.uk/browse/ODPR-1256)
[ODPR-1276](https://jira.tools.tax.service.gov.uk/browse/ODPR-1276)
[ODPR-1277](https://jira.tools.tax.service.gov.uk/browse/ODPR-1277)
[ODPR-1279](https://jira.tools.tax.service.gov.uk/browse/ODPR-1287)

[ODPR- 1256]: flagged issues

---

app/controllers/IndividualIdentityConfirmedController.scala
app/pages/DateOfBirthPage.scala
app/pages/IndividualIdentityConfirmedPage.scala
app/views/IndividualIdentityConfirmedView.scala.html
conf/app.routes
conf/messages.en
test/controllers/IndividualIdentityConfirmedControllerSpec.scala
test/pages/DateOfBirthPageSpec.scala
test/pages/IndividualIdentityConfirmedPageSpec.scala

- individual identity confirmed screen
[ODPR-1208](https://jira.tools.tax.service.gov.uk/browse/ODPR-1208)

[ODPR-1208] - REG-19 Individual Identity Confirmed

---

app/controllers/IndividualIdentityNotConfirmedController.scala
app/pages/DateOfBirthPage.scala
app/views/IndividualIdentityNotConfirmedView.scala.html
conf/app.routes
conf/messages.en
test/controllers/IndividualIdentityNotConfirmedControllerSpec.scala
test/pages/DateOfBirthPageSpec.scala

renames 'identityNotConfirmed' to 'individualIdentityNotConfirmed'
[ODPR-1237](https://jira.tools.tax.service.gov.uk/browse/ODPR-1237)

[ODPR-1237] - REG-KO-8.Renamed to IndividualIdentityNotConfirmed

---

app/connectors/RegistrationConnector.scala
app/controllers/InternationalAddressController.scala
app/controllers/UkAddressController.scala
app/models/registration/Address.scala
app/models/registration/requests/IndividualWithoutId.scala
project/AppDependencies.scala
test-utils/builders/IndividualWithoutIdBuilder.scala
test-utils/builders/InternationalAddressBuilder.scala
test-utils/builders/UkAddressBuilder.scala
test/controllers/InternationalAddressControllerSpec.scala
test/controllers/UkAddressControllerSpec.scala
test/models/registration/AddressSpec.scala
test/models/registration/requests/IndividualWithoutIdSpec.scala

[ODPR-1370](https://jira.tools.tax.service.gov.uk/browse/ODPR-1370)

[ODPR-1370] - Registration calls at the end of individual journeys.

---

app/forms/PrimaryContactNameFormProvider.scala
app/forms/SecondaryContactNameFormProvider.scala
app/forms/common/Validation.scala
test-utils/generators/Generators.scala
test/forms/PrimaryContactNameFormProviderSpec.scala
test/forms/SecondaryContactNameFormProviderSpec.scala

Rename regex validation

---

app/forms/BusinessEnterTradingNameFormProvider.scala
app/forms/BusinessNameFormProvider.scala
app/forms/BusinessNameNoUtrFormProvider.scala
test/forms/BusinessEnterTradingNameFormProviderSpec.scala
test/forms/BusinessNameFormProviderSpec.scala
test/forms/BusinessNameNoUtrFormProviderSpec.scala

[ODPR-1385](https://jira.tools.tax.service.gov.uk/browse/ODPR-1385)

[ODPR-1385] - Organisation name should be 105 characters.

---

app/config/CryptoProvider.scala
app/config/FrontendAppConfig.scala
app/config/Module.scala
app/models/UserAnswers.scala
app/models/registration/responses/RegistrationResponse.scala
app/repositories/SessionRepository.scala
conf/application.conf
it/test/repositories/SessionRepositorySpec.scala
project/AppDependencies.scala
test/models/registration/responses/RegistrationResponseSpec.scala

[ODPR-1375](https://jira.tools.tax.service.gov.uk/browse/ODPR-1375)

[ODPR-1375] - Encrypt relevant parts of user answers

---

app/forms/BusinessEnterTradingNameFormProvider.scala
conf/messages.en
test/forms/BusinessEnterTradingNameFormProviderSpec.scala

[ODPR-1385] - Fixes error messages

---

app/models/pageviews/CheckYourAnswersOrganisationViewModel.scala
project/AppDependencies.scala
project/plugins.sbt
test/controllers/CheckYourAnswersControllerSpec.scala

https://jira.tools.tax.service.gov.uk/browse/ODPR-1361

ODPR-1361 Fixes bug where Org-Without Id cannot reach checkYourAnswers

---

app/controllers/CheckYourAnswersController.scala
app/models/UserAnswers.scala
app/models/registration/Address.scala
app/models/registration/requests/IndividualWithoutId.scala
app/models/registration/requests/OrganisationWithoutId.scala
app/models/registration/responses/MatchResponse.scala
app/models/registration/responses/MatchResponseWithId.scala
app/models/subscription/Contact.scala
app/models/subscription/requests/SubscriptionRequest.scala
app/models/subscription/responses/SubscriptionResponse.scala
app/pages/CheckYourAnswersPage.scala
app/views/CheckYourAnswersIndividualView.scala.html
app/views/CheckYourAnswersOrganisationView.scala.html
conf/app.routes
conf/messages.en
it/test/repositories/SessionRepositorySpec.scala
test/controllers/CheckYourAnswersControllerSpec.scala
test/models/registration/AddressSpec.scala
test/models/registration/requests/IndividualWithoutIdSpec.scala
test/models/registration/requests/OrganisationWithoutIdSpec.scala
test/models/subscription/IndividualSpec.scala
test/models/subscription/requests/SubscriptionRequestSpec.scala
test/pages/CheckYourAnswersPageSpec.scala

[ODPR-1277](https://jira.tools.tax.service.gov.uk/browse/ODPR-1277)

[ODPR-1277] -DEV: SUB-11. Organisation/Individual check your answers.

---

app/controllers/CheckYourAnswersController.scala
app/models/SubscriptionDetails.scala
app/models/UserAnswers.scala
app/models/subscription/requests/SubscriptionRequest.scala
app/pages/CheckYourAnswersPage.scala
test/controllers/CheckYourAnswersControllerSpec.scala
test/models/SubscriptionDetailsSpec.scala
test/pages/CheckYourAnswersPageSpec.scala

Store subscription details after subscribing

---

conf/messages.en

Changes label to 'Trading name'

---

app/forms/common/Validation.scala
test-utils/generators/Generators.scala

Fix text input regex

---

app/controllers/CheckYourAnswersController.scala
app/models/SubscriptionDetails.scala
app/pages/CheckYourAnswersPage.scala
project/AppDependencies.scala
test-utils/builders/OrganisationContactBuilder.scala
test-utils/builders/SubscriptionDetailsBuilder.scala
test-utils/builders/SubscriptionRequestBuilder.scala
test/controllers/CheckYourAnswersControllerSpec.scala
test/controllers/PrimaryContactPhoneNumberControllerSpec.scala
test/controllers/SecondaryContactPhoneNumberControllerSpec.scala
test/forms/PrimaryContactPhoneNumberFormProviderSpec.scala
test/forms/SecondaryContactPhoneNumberFormProviderSpec.scala
test/models/SubscriptionDetailsSpec.scala
test/models/pageviews/PrimaryContactPhoneNumberViewModelSpec.scala
test/models/pageviews/RegistrationConfirmationViewModelSpec.scala
test/models/pageviews/SecondaryContactPhoneNumberViewModelSpec.scala
test/pages/CheckYourAnswersPageSpec.scala

[ODPR-1443](https://jira.tools.tax.service.gov.uk/browse/ODPR-1443)

[ODPR-1443] DEV: Analyse how to get to KO screens when subscribing

---

app/views/UtrCorporationTaxView.scala.html
app/views/UtrPartnershipView.scala.html
app/views/UtrSelfAssessmentView.scala.html
conf/messages.en

- Update to content
[ODPR-1420](https://jira.tools.tax.service.gov.uk/browse/ODPR-1420)

[ODPR-1420] - REG-6.Content update

---

app/connectors/RegistrationConnector.scala
app/controllers/CheckYourAnswersController.scala
app/models/audit/AuditEventModel.scala
app/services/AuditService.scala
project/AppDependencies.scala
test/controllers/CheckYourAnswersControllerSpec.scala
test/models/audit/AuditEventModelSpec.scala
test/services/AuditServiceSpec.scala

[ODPR-1346](https://jira.tools.tax.service.gov.uk/browse/ODPR-1346)

[ODPR-1346] - Create configuration for auditing.

---

app/controllers/CheckYourAnswersController.scala
app/models/audit/AuditEventModel.scala
test/controllers/CheckYourAnswersControllerSpec.scala
test/models/audit/AuditEventModelSpec.scala

[ODPR-1346] - Fixes AutuSubscription event.

---

app/views/RegistrationConfirmationView.scala.html

Add fullstop on confirmation page

---

app/models/registration/Address.scala
app/models/registration/requests/OrganisationWithoutId.scala
app/views/ViewUtils.scala
it/test/connectors/RegistrationConnectorSpec.scala
test-utils/builders/OrganisationWithoutIdBuilder.scala
test/models/registration/AddressSpec.scala
test/models/registration/requests/IndividualWithoutIdSpec.scala
test/models/registration/requests/RegistrationRequestSpec.scala
test/models/registration/responses/RegistrationResponseSpec.scala
test/pages/BusinessNamePageSpec.scala
test/pages/RegistrationTypePageSpec.scala
test/pages/SoleTraderNamePageSpec.scala
test/views/ViewUtilsSpec.scala

[FIX] ATS_Bug073.

---

app/connectors/EnrolmentStoreConnector.scala
it/test/connectors/EnrolmentStoreConnectorSpec.scala

[ODPR-1514] - Fixes tax-entrolments url.

---

app/connectors/TaxEnrolmentConnector.scala
app/controllers/CheckYourAnswersController.scala
app/controllers/actions/IdentifierAction.scala
app/models/User.scala
app/models/eacd/requests/EnrolmentKnownFacts.scala
app/models/eacd/requests/GroupEnrolment.scala
it/test/connectors/TaxEnrolmentConnectorSpec.scala
test-utils/builders/EnrolmentKnownFactsBuilder.scala
test-utils/builders/GroupEnrolmentBuilder.scala
test-utils/generators/ModelGenerators.scala
test/controllers/CheckYourAnswersControllerSpec.scala
test/models/eacd/requests/EnrolmentKnownFactsSpec.scala
test/models/eacd/requests/GroupEnrolmentSpec.scala

[ODPR-1514] - Uses enrolments with verifiers.

---

app/views/RegistrationTypeView.scala.html
conf/messages.en

- Content update
[ODPR-1543](https://jira.tools.tax.service.gov.uk/browse/ODPR-1543)

[ODPR-1543] - REG-2 content update

---

app/connectors/TaxEnrolmentConnector.scala
app/services/UuidService.scala

[ODPR-1514] - Provides additional headers.

---

app/services/EnrolmentService.scala

Does not throw error if enrolment fails

---

conf/messages.en

Update service name

---

app/config/AppConfig.scala
app/connectors/UserAllowListConnector.scala
app/controllers/actions/IdentifierAction.scala
app/services/UserAllowListService.scala
conf/application.conf
it/test/connectors/UserAllowListConnectorSpec.scala
test/controllers/actions/AuthActionSpec.scala
test/services/UserAllowListServiceSpec.scala

Add user allowlist

---

app/config/AppConfig.scala
conf/application.conf

Fix exit survey URL

---

app/views/IndividualIdentityNotConfirmedView.scala.html
conf/messages.en

- REG-KO-8 content changes
- Has journey test update: https://github.com/hmrc/digital-platform-reporting-ui-tests/pull/55
[ODPR-1554](https://jira.tools.tax.service.gov.uk/browse/ODPR-1554)

[ODPR-1554] - REG-KO-8 content changes

---

app/views/UnauthorisedView.scala.html

Remove empty content from unauthorised page

---

app/controllers/DateOfBirthController.scala
app/models/registration/requests/IndividualWithNino.scala
app/pages/DateOfBirthPage.scala
app/views/BusinessAlreadyRegisteredView.scala.html
app/views/BusinessDetailsDoNotMatchView.scala.html
app/views/IndividualAlreadyRegisteredView.scala.html
app/views/IndividualIdentityNotConfirmedView.scala.html
app/views/JourneyRecoveryContinueView.scala.html
app/views/JourneyRecoveryStartAgainView.scala.html
test-utils/generators/ModelGenerators.scala
test/controllers/DateOfBirthControllerSpec.scala
test/models/registration/requests/IndividualWithNinoSpec.scala
test/pages/DateOfBirthPageSpec.scala

Fix registration for CL250 users

---

app/views/CheckYourAnswersIndividualView.scala.html
app/views/CheckYourAnswersOrganisationView.scala.html

Prevent double clicks when subscribing

---

test/forms/ClaimEnrolmentFormProviderSpec.scala

Fix intermittent test failure

---

app/views/SecondaryContactEmailAddressView.scala.html
conf/messages.en

- removal of p1 in secondary contact email address page
[ODPR-1708](https://jira.tools.tax.service.gov.uk/browse/ODPR-1708)

[ODPR-1708] - SUB-8 remove p1

---

conf/messages.en

[ODPR-1745] - update service.name

---

app/views/RegistrationConfirmationView.scala.html
app/views/SecondaryContactEmailAddressView.scala.html
conf/messages.en

ODPR-1744 - Snagging 1.1

---

conf/application.conf

[ODPR-1768] - dprs accessibility statement

---

app/forms/common/Validation.scala
test/forms/IndividualEmailAddressFormProviderSpec.scala
test/forms/PrimaryContactEmailAddressFormProviderSpec.scala
test/forms/SecondaryContactEmailAddressFormProviderSpec.scala

ODPR-1781 Email validation regex changed

---

app/forms/common/Validation.scala
test-utils/generators/Generators.scala

ODPR-1793 - add ! input validation

---

app/views/BusinessAddressView.scala.html
app/views/InternationalAddressView.scala.html
app/views/UkAddressView.scala.html
app/views/ViewUtils.scala
project/AppDependencies.scala

ODPR-1783 - added List Box Accessible Name

---

app/views/RegisteredInUkView.scala.html
conf/messages.en
project/AppDependencies.scala

[ODPR-1824] - Hint Text Unprogmatically linked to Radio Buttons

---

app/models/CountriesList.scala
app/models/Country.scala
test/models/CountriesListSpec.scala

[FIX] Uses Isle of Man, instead of The Isle of Man.

---

project/build.properties
project/plugins.sbt

[ODPR-1754] - Fix Warnings in the code

---

app/pages/BusinessTypePage.scala

Removes forgotten todo

---

app/forms/common/Validation.scala

Removes comments

---

app/views/BusinessAlreadyRegisteredView.scala.html
app/views/BusinessDetailsMatchOtherView.scala.html
app/views/CannotUseServiceAgentView.scala.html
app/views/CannotUseServiceIndividualView.scala.html
app/views/CannotUseServiceThirdPartyIndividualView.scala.html
app/views/CannotUseServiceThirdPartyOrganisationView.scala.html
app/views/IndividualAlreadyRegisteredView.scala.html
conf/messages.en
project/AppDependencies.scala

[ODPR-1862] - Make Sign In links configurable.

---

app/config/AppConfig.scala
app/views/templates/Layout.scala.html
project/AppDependencies.scala
project/build.properties

[ODPR-1872] - Removes Beta banner.

---

conf/logback.xml

	DLS-11574 Update application logging to live services standard

---

app/repositories/SessionRepository.scala
build.sbt
conf/application.conf
project/AppDependencies.scala
project/plugins.sbt

https://jira.tools.tax.service.gov.uk/browse/DLS-12194

DLS-12194: Gov UK Brand refresh
